# Generated by Django 4.2.13 on 2024-05-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_chatrooms_alter_chatroom_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
